services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: linkkeeper
    ports: ["5432:5432"]

  user-service:
    build:
      context: .
      dockerfile: build/user-service/Dockerfile
    command: ["./user-service"]
    environment:
      HTTP_ADDR: ":8081"
      POSTGRES_DSN: "postgres://postgres:postgres@postgres:5432/linkkeeper?sslmode=disable"
    depends_on: [postgres]
    ports: ["8081:8081"]

  api-service:
    build:
      context: .
      dockerfile: build/api-service/Dockerfile
    command: ["./api-service"]
    environment:
      HTTP_ADDR: ":8080"
      POSTGRES_DSN: "postgres://postgres:postgres@postgres:5432/linkkeeper?sslmode=disable"
    depends_on: [postgres]
    ports: ["8080:8080"]

  bot-service:
    build:
      context: .
      dockerfile: build/bot-service/Dockerfile
    command: ["./bot-service"]
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      API_BASE_URL: "http://api-service:8080"
      USER_SERVICE_URL: "http://user-service:8081"
    depends_on: [api-service, user-service]
